In [1]:
print("Hello World")

Hello World


In [1]:
import torch
import numpy as np

In [3]:
a = np.array(
    [[1, 2],
     [3, 4]]
)
b = np.array(
    [[4, 3],
     [2, 1]]
)
np.dot(a,b)

array([[ 8,  5],
       [20, 13]])

In [26]:
c=torch.arange(24).reshape(2,3,4)
c, c.sum(axis=0)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]))

In [19]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
sum_A = A.sum(axis=0)
A.shape, sum_A.shape, A, sum_A

(torch.Size([4, 5]),
 torch.Size([5]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([30., 34., 38., 42., 46.]))

In [20]:
A/sum_A

tensor([[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
        [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
        [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
        [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]])

In [30]:
A=torch.ones((3,4))
B=A.sum(axis=1,keepdim=True)
B

tensor([[4.],
        [4.],
        [4.]])

In [1]:
import torchvision

D:\exe_code\Python\10_动手学深度学习\venv\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\exe_code\Python\10_动手学深度学习\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


In [8]:
import math

x = np.arange(-1, 2, 0.01)
x=2
x ** -1

0.5

In [11]:
y=list(np.arange(-10, 10, 0.5))
y.

-10.0

In [13]:
list?